import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const jakartaSans = Plus_Jakarta_Sans({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${jakartaSans.className}`}
			>
				<div className="grid grid-rows-[auto_1fr] md:grid-cols-[240px_1fr] md:grid-rows-1">
					<Nav />
					<main>{children}</main>
				</div>
			</body>
		</html>
	);
}
